apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "helm-flask-svc.fullname" . }}-init"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'echo "Running pre-install hook: setting up init..."']
      restartPolicy: Never
